export const SEARCH_QUERY_UPDATE ='SEARCH_QUERY_UPDATE';
export const SEARCH_QUERY = 'SEARCH_QUERY';
export const CHECKBOX_CLICK = 'CHECKBOX_CLICK';
export const REMOVE_BADGE = 'REMOVE_BADGE';
export const CHANGE_SORT_VALUE = 'CHANGE_SORT_VALUE';
export const FILTER_QUERY = 'FILTER_QUERY';

